//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Congratulation
{
	private string adressPicture
	{
		get;
		set;
	}

	private String[] cliche
	{
		get;
		set;
	}

	private String[] verselet
	{
		get;
		set;
	}

	public virtual void Cogratulation(string kAdressPicture, string kCliche, string kVerselet)
	{
		throw new System.NotImplementedException();
	}

	public virtual String getAdressPicture()
	{
		throw new System.NotImplementedException();
        return adressPicture;
	}

	public virtual String[] getCliche()
	{
		throw new System.NotImplementedException();
        return cliche;
	}

	public virtual String[] getVerselet()
	{
		throw new System.NotImplementedException();
        return verselet;
	}

	public virtual void showCongratulatiion()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getData()
	{
		throw new System.NotImplementedException();
	}

}

