//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Human
{
	private string holiday
	{
		get;
		set;
	}

	private bool sex
	{
		get;
		set;
	}

	private int age
	{
		get;
		set;
	}

	private string handling
	{
		get;
		set;
	}

	private string name
	{
		get;
		set;
	}

	private String[] interests
	{
		get;
		set;
	}

	public Human(string kName, string kHandling, int kAge, bool kSex, string kInterests, string kHoliday)
	{
	}

	public Human(string kName, string kHandling, int kAge, bool kSex, string kHoliday)
	{
	}

	public virtual Congratulation generationCongratulation()
	{
        Congratulation newObj = new Congratulation();
		throw new System.NotImplementedException();
        return newObj;
	}

}

